#before_install:
#  - npm i -g npm@version
sudo: false
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "lts/*"
#  - "node" // there is an issue with node 11.11.0 and jest ( TypeError: Cannot assign to read only property 'Symbol(Symbol.toStringTag)' of object '#<process>')

jobs:
  include:
    - stage: validity
      name: "Linting"
      script: npm run lint
    - stage: validity
      name: "Unit tests"
      script: npm run test-coverage && npm run report-coverage
    - stage: compile&test-e2e
      script: npm run test-e2e-latest
